services:
  app:
    container_name: url-shortener-app
    restart: unless-stopped
    image: ghcr.io/hectorzr/url-shortener:latest
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      ENV: ${ENV}
      PORT: ${PORT}
      HOST: ${HOST}
      PATH_PREFIX: ${PATH_PREFIX}
      GOOGLE_CREDENTIALS_JSON: ${GOOGLE_CREDENTIALS_JSON}
      PROJECT_ID: ${PROJECT_ID}
      SITE_KEY: ${SITE_KEY}
      SECRET_KEY: ${SECRET_KEY}
      CAPTCHA_ACTION: ${CAPTCHA_ACTION}
    networks:
      - proxy
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.url-shortener.rule=Host(`shortener.${HOST}`)"
      - "traefik.http.services.url-shortener.loadbalancer.server.port=${PORT}"
      - "traefik.http.routers.url-shortener.entrypoints=websecure"
      - "traefik.http.routers.url-shortener.tls=true"
      - "traefik.http.routers.url-shortener.tls.certresolver=le"

  db:
    image: postgres:16.9
    restart: always
    container_name: url-shortener-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - url-shortener-data:/var/lib/postgresql/data
    networks:
      - default

volumes:
  url-shortener-data:
    driver: local

networks:
  proxy:
    name: proxy
    external: true
