services:
  app:
    container_name: url-shortener-app
    restart: unless-stopped
    image: ghcr.io/hectorzr/url-shortener:latest
    command: ["./app"]
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      ENV: ${ENV}
      PORT: ${PORT}
      HOST: ${HOST}
    develop:
      watch:
        - action: sync
          path: .
          target: /code
    networks:
      - proxy
      - default
    labels:
      - "traefik.http.routers.url-shortener.rule=Host(`shortener.${HOST}`)"
      - "traefik.http.services.url-shortener.loadbalancer.server.port=${PORT}"
      - "traefik.http.routers.url-shortener.entrypoints=websecure"
      - "traefik.http.routers.url-shortener.tls=true"

  db:
    image: postgres:16.9
    restart: always
    container_name: url-shortener-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - url-shortener-data:/var/lib/postgresql/data
    networks:
      - default

volumes:
  url-shortener-data:
    driver: local

networks:
  proxy:
    external: true
